# SECTION A: 15 MARKS

 _________________

### 1.	Write a Program to

A.	Create a list of numbers from 1 to 10 in python (do not hardcode numbers). (1 MARKS)

B.	Find the number of elements present in the list. (1 MARKS)

C.	Convert the above list into a series. (1 MARKS)

D.	Display the elements at even position (as per the index values). (1 MARKS)

E.	Add the elements 11,12 and 13 to the existing series. (1 MARKS)


1.A


In [3]:
no = list(range(1,10))
no

[1, 2, 3, 4, 5, 6, 7, 8, 9]

1.B

In [5]:
len(no)

9

1.C

In [10]:
import numpy as np
import pandas as pd

x= pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9])
x

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

1.D

In [11]:
x[::2]

0    1
2    3
4    5
6    7
8    9
dtype: int64

1.E

In [15]:
y=pd.Series([11,12,13],index=[10,11,12])
z=x.append(y)
print(z)

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
10    11
11    12
12    13
dtype: int64


### 2. Write a Program to



A. Write a code snippet to create a numpy array with elements between 12 and 36 which has a difference of 2 between two consecutive numbers (no hardcoding of values allowed). Display the contents of the array. (1 Marks) 
 
B.	Write a code snippet to convert the above-mentioned 1-D array into an array of dimension 3x4. (1 Marks) 
 
C.	Write a code snippet to fetch the elements present in the 2nd to 4th position of 2nd row from the above-created data frame. Store the result set in a variable. (1 Marks) 
 
d.What will be the output for the following code?

def func(x):

    return lambda y: (x ** y)+(y + 1)

func5 = func(5)

func5(2)

e.What will be the result of the following Python Code?

    5%2 > 1 or 4/2 !=2
 
f. What is the output for the following program?

A = “20”

B = “20”

C = A+B

print(C)

g.What is the output of the following code:

x= [15,18]
y= [6,7]
x+y


2.A

In [88]:
x = np.arange(12,36,2)
print(x)
print()

[12 14 16 18 20 22 24 26 28 30 32 34]



2.B

In [90]:
x=x.reshape(3,4)
print(x)
print()

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]



2.C

In [92]:
result = x[1:2,1:]
print(result)
print()

[[22 24 26]]



2.D

In [1]:
28

28

2.E

In [2]:
False

False

2.F

In [3]:
2020

2020

2.G

In [4]:
 [15, 18, 6, 7]

[15, 18, 6, 7]

# SECTION B : 30 Marks
1.There is a wood log cutting factory. We are calculating the revenue and the no. of pieces that the wood is cut into. We are given a wood log of length n cms and a table of prices p[i] for i = 1, 2, …, n. Here p[i] is the price of a wood log of length ’i’ cms. We have to find the optimal way of cutting the wood log to make the furniture so that maximum revenue can be generated by selling the pieces of wood. (15 MARKS)

In [1]:
def wood_log(p, n):
   
    # r[i] is the maximum revenue for rod length i
    # r[i] = -1 means that r[i] has not been calculated yet
    r = [-1]*(n + 1)
    r[0] = 0
 
    # s[i] is the length of the initial cut needed for rod length i
   
    s = [-1]*(n + 1)
 
    for i in range(1, n + 1):
        q = -1
        for j in range(1, i + 1):
            temp = p[j] + r[i - j]
            if q < temp:
                q = temp
                s[i] = j
        r[i] = q
 
    return r, s
 
 
n = int(input(' length of the wood log in cms: '))
 
# p[i] is the price of a wood log of length i
# p[0] is not needed, so it is set to None
p = [None]
for i in range(1, n + 1):
    price = input(' price of a wood log of length {} in: '.format(i))
    p.append(int(price))
 
r, s = wood_log(p, n)
print('The maximum revenue that can be obtained:', r[n])
print('The rod needs to be cut into length(s) of ', end='')
while n > 0:
    print(s[n], end=' ')
    n -= s[n]

 length of the wood log in cms: 4
 price of a wood log of length 1 in: 10
 price of a wood log of length 2 in: 20
 price of a wood log of length 3 in: 304
 price of a wood log of length 4 in: 40
The maximum revenue that can be obtained: 314
The rod needs to be cut into length(s) of 1 3 

 2. Create a scientific calculator using python. The calculator should give a menu to the user asking the type of mathematical operation to be performed (1. Arithmetic 2. Trigonometric 3. Logarithmic). According to the choice of the user, operations are performed on the numbers entered. Any innovation in this basic calculator model will be given more marks. (15 MARKS) SAMPLE INPUT: SCIENTIFIC CALCULATOR

ARITHMETIC 2. TRIGNOMETRIC
Please select an option of your choice1 Enter the first number23

Enter the second number56

1.Addition 2. Subtraction 3. Multiplication 4. Division Please input the number of your choice of operation4 SAMPLE OUTPUT: The division of the first number with the second numbers is 0.4107142857142857

In [4]:
inp = int(input('Enter the operations to be performed(1 for Arithmetic,2 for Trignometric,3 for Logarithmic)'))
if inp==1:
    num1=int(input('enter the first number'))
    num2=int(input('enter the second number'))
    inp2=int(input('Please input the number of your choice of operation 1.Addition 2. Subtraction 3. Multiplication 4. Division'))
    if inp2==1:
        a=num1+num2
        print('The Addition of the first number with the second numbers is %d'%(a))
    elif inp2==2:
        a=num1-num2
        print('The Subtraction of the first number with the second numbers is %d'%(a))
    elif inp2==3:
        a=num1*num2
        print('The Multiplication of the first number with the second numbers is {}'.format(a))
    elif inp2==4:
        a=num1/num2
        print('The Multiplication of the first number with the second numbers is {}'.format(a))
    else:
        print('enter a valid input')
elif inp==2:
    print('Trignometric functions are to be performed')
elif inp==3:
    print('Logarithmic functions are to be performed')
else:
    print('enter a valid input')

Enter the operations to be performed(1 for Arithmetic,2 for Trignometric,3 for Logarithmic)1
enter the first number3
enter the second number4
Please input the number of your choice of operation 1.Addition 2. Subtraction 3. Multiplication 4. Division1
The Addition of the first number with the second numbers is 7
